#!/bin/bash
# -----------------------------------------------------------------------------
# docker-mumble /start script
#
# Authors: Isaac Bythewood
# Updated: Oct 20th, 2014
# -----------------------------------------------------------------------------


# Set Mumble SuperUser password
if [ ! -f /mumble/superuser_password.txt ]
then
    SUPERUSER_PASSWORD=`pwgen -c -n -1 15`
    echo $SUPERUSER_PASSWORD > /mumble/superuser_password.txt
    murmurd -ini /mumble/mumble-server.ini -supw $SUPERUSER_PASSWORD
    sleep 3
    echo
    echo "# ------------------------------------------------------------------------------"
    echo "# SuperUser Password"
    echo "#"
    echo "# Password: $SUPERUSER_PASSWORD"
    echo "#"
    echo "# Connect to the server as SuperUser and setup an admin user."
    echo "# ------------------------------------------------------------------------------"
    echo
fi


# Run supervisor which maintains the mumble server
/usr/bin/supervisord -c /etc/supervisor/supervisord.conf

